---
# task file to install/update/configure ntp on Debian based systems

- name: APT | Ensure ntp is installed and up-to-date
  become: true
  become_user: root
  apt:
    name: chrony
    state: present
    update_cache: true

- name: TEMPLATE | Template the etc/chrony.conf file
  become: true
  become_user: root
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'

- name: STAT | Check if ntp service exists
  stat:
    path: /usr/lib/systemd/system/ntpd.service
  register: chrony_ntp

- name: SYSTEMD | Ensure ntpd is stopped and disabled
  become: true
  systemd:
    name: ntpd
    enabled: false
    state: stopped
    daemon_reload: true
  when: ntp_chrony.stat.exists

- name: SYSTEMD | Ensure chronyd is started and enabled
  become: true
  systemd:
    name: chronyd
    enabled: true
    state: restarted
    daemon_reload: true

- name: STAT | Check if ufw service exists
  stat:
    path: /usr/sbin/ufw
  register: firewall

- name: UFW | Ensure NTP Service is enabled in firewall
  become: true
  become_user: root
  command: 'ufw allow ntp'
  when:
    - firewall is defined
#    - firewall_status.rc == 0
